CREATE TABLE TALLER
(
	ID NUMERIC(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(280) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(400) NOT NULL ,
	DURACION NUMERIC(2) NOT NULL,
	ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

create sequence SEQ_TALLER;

  INSERT INTO TALLER(ID,NOMBRE,DESCRIPCION,DURACION)
  VALUES(1,'Java 11','Nuesvas características',20);
  
  INSERT INTO TALLER(ID,NOMBRE,DESCRIPCION,DURACION) 
  VALUES(2,'Angular 7','Mejoras en arquitectura',20);
  
  COMMIT;
  
  SELECT ID,NOMBRE,DESCRIPCION,DURACION,ESTADO FROM TALLER;
